# Generated by Django 3.1 on 2020-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderreceived', 'orderreceived'), ('dispatched', 'dispatched'), ('delivered', 'delivered')], default='orderreceived', max_length=120),
        ),
    ]
